### PR TITLE
Flatpak fixes

### PR DESCRIPTION
**Pull request by leamas**
Fixes for installation problems:
  - Rebuilds libusb-0.1 from source on all architectures. This is done using libusb-compat-0.1, a thin  layer on the ubiquitous libusb-1.0 rather than the original libusb-.01 sources. The layer has been used in Fedora, so it should be battle-hardened.
  - Add an architecture aware flatpak installation script to get proper binaries in the right location.
  - Remove various unused and outdated cruft.

I have no dongle (should get one, I know), so this definitely need testing.

It the libusb setup works, we should probably implement it also on native Debian. It shouldn't be that complicated.

### CODE REVIEW

**Comment by bdbcat** [comment]
Can I apply this before #7, for testing?

**Comment by leamas** [comment]
This is the idea, I'll rebase  once we sorted out this which is a more urgent fix.

**Comment by bdbcat** [comment]
@leamas 
The latest build 0.9.0.23 works fine on aarch64/20.08.  Dongle works too.
Only oddity is that the "ip" build leaves a lot of cruft in the "bin" directory.
cruft
 directory.

**Comment by leamas** [comment]
Should be fixed by #9. Still don't understand why it's needed, though.

**Pull request merged**
